export {default as spfc} from "./paulistano2.png"
export {default as menuSvg} from "./menu.svg"
export {default as cart} from "./cart.svg"
export {default as boot} from "./boot.webp"
export {default as arrowRight} from "./rearrow.svg"
export {default as arrowRightBlack} from "./rearrowblack.svg"